name: hello-world
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
      - name: Adding markdown
        run: echo '### Hello world! ðŸš€' >> $GITHUB_STEP_SUMMARY
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
  my-job:
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: justinianus-learn-projects/actions-learning-pathway/.github/workflows/build-test-deploy.yml@main
    with:
      node-version: '18.x'
